import base64
import json
import subprocess

# Paste your cookie value here (without the 'base64-' prefix)
cookie_value = "eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0ltdHBaQ0k2SW1OdlJWTlhTMlZLVlRKeE0xaEdUMWdpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBjM01pT2lKb2RIUndjem92TDNGcmRXVnlZbmhvWW0xdWJIUjZlbmRvY1hSMUxuTjFjR0ZpWVhObExtTnZMMkYxZEdndmRqRWlMQ0p6ZFdJaU9pSXlNMk5pTURZMVlTMDRZamRrTFRRMk5EQXRPRGxtWWkxaFkyTmtabVkyT0dFNE1qTWlMQ0poZFdRaU9pSmhkWFJvWlc1MGFXTmhkR1ZrSWl3aVpYaHdJam94TnpVd01ESXdOREF6TENKcFlYUWlPakUzTlRBd01UWTRNRE1zSW1WdFlXbHNJam9pYlhrdVptOXlkMkZ5WkdsdVoyVnRZV2xzUUdkdFlXbHNMbU52YlNJc0luQm9iMjVsSWpvaUlpd2lZWEJ3WDIxbGRHRmtZWFJoSWpwN0luQnliM1pwWkdWeUlqb2laVzFoYVd3aUxDSndjbTkyYVdSbGNuTWlPbHNpWlcxaGFXd2lYWDBzSW5WelpYSmZiV1YwWVdSaGRHRWlPbnNpWlcxaGFXd2lPaUp0ZVM1bWIzSjNZWEprYVc1blpXMWhhV3hBWjIxaGFXd3VZMjl0SWl3aVpXMWhhV3hmZG1WeWFXWnBaV1FpT25SeWRXVXNJbkJvYjI1bFgzWmxjbWxtYVdWa0lqcG1ZV3h6WlN3aWMzVmlJam9pTWpOallqQTJOV0V0T0dJM1pDMDBOalF3TFRnNVptSXRZV05qWkdabU5qaGhPREl6SW4wc0luSnZiR1VpT2lKaGRYUm9aVzUwYVdOaGRHVmtJaXdpWVdGc0lqb2lZV0ZzTVNJc0ltRnRjaUk2VzNzaWJXVjBhRzlrSWpvaWNHRnpjM2R2Y21RaUxDSjBhVzFsYzNSaGJYQWlPakUzTkRrNU9UY3pNVEY5WFN3aWMyVnpjMmx2Ymw5cFpDSTZJbVV3WmpCa016UTNMV1EyTTJVdE5HRmtZUzA1T0RZNExUazFOMlJsTUdZMU5tTXdOeUlzSW1selgyRnViMjU1Ylc5MWN5STZabUZzYzJWOS5Xb0Rtd2g1RmxUYWhKX1VhVzNJUmVab2FEQXZLanJCNEEtQmNhRjRKUDlzIiwidG9rZW5fdHlwZSI6ImJlYXJlciIsImV4cGlyZXNfaW4iOjM2MDAsImV4cGlyZXNfYXQiOjE3NTAwMjA0MDMsInJlZnJlc2hfdG9rZW4iOiI3Y2d4Z3lnbnppZGwiLCJ1c2VyIjp7ImlkIjoiMjNjYjA2NWEtOGI3ZC00NjQwLTg5ZmItYWNjZGZmNjhhODIzIiwiYXVkIjoiYXV0aGVudGljYXRlZCIsInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiZW1haWwiOiJteS5mb3J3YXJkaW5nZW1haWxAZ21haWwuY29tIiwiZW1haWxfY29uZmlybWVkX2F0IjoiMjAyNS0wNi0xNVQxNDowMjo0My40NjY1MThaIiwicGhvbmUiOiIiLCJjb25maXJtYXRpb25fc2VudF9hdCI6IjIwMjUtMDYtMTVUMTQ6MDI6MTUuMzM1NjQ4WiIsImNvbmZpcm1lZF9hdCI6IjIwMjUtMDYtMTVUMTQ6MDI6NDMuNDY2NTE4WiIsImxhc3Rfc2lnbl9pbl9hdCI6IjIwMjUtMDYtMTVUMTQ6MjE6NTEuNDk3ODk5WiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoibXkuZm9yd2FyZGluZ2VtYWlsQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjIzY2IwNjVhLThiN2QtNDY0MC04OWZiLWFjY2RmZjY4YTgyMyJ9LCJpZGVudGl0aWVzIjpbeyJpZGVudGl0eV9pZCI6ImVmOTFmZDllLTU3NjktNDk0NS1iMjBlLTg2ZmFjNmQ0N2JmMSIsImlkIjoiMjNjYjA2NWEtOGI3ZC00NjQwLTg5ZmItYWNjZGZmNjhhODIzIiwidXNlcl9pZCI6IjIzY2IwNjVhLThiN2QtNDY0MC04OWZiLWFjY2RmZjY4YTgyMyIsImlkZW50aXR5X2RhdGEiOnsiZW1haWwiOiJteS5mb3J3YXJkaW5nZW1haWxAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMjNjYjA2NWEtOGI3ZC00NjQwLTg5ZmItYWNjZGZmNjhhODIzIn0sInByb3ZpZGVyIjoiZW1haWwiLCJsYXN0X3NpZ25faW5fYXQiOiIyMDI1LTA2LTE1VDE0OjAyOjE1LjMyOTk2WiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA2LTE1VDE0OjAyOjE1LjMzMDAxWiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA2LTE1VDE0OjAyOjE1LjMzMDAxWiIsImVtYWlsIjoibXkuZm9yd2FyZGluZ2VtYWlsQGdtYWlsLmNvbSJ9XSwiY3JlYXRlZF9hdCI6IjIwMjUtMDYtMTVUMTQ6MDI6MTUuMzEzNTI4WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA2LTE1VDE5OjQ2OjQzLjE4NTkwNloiLCJpc19hbm9ueW1vdXMiOmZhbHNlfX0"

# Decode base64 (strip the 'base64-' prefix if present)
if cookie_value.startswith("base64-"):
    cookie_value = cookie_value[len("base64-"):]

decoded = base64.b64decode(cookie_value + "==")  # Add padding if needed
json_data = json.loads(decoded)

# Extract the access token
access_token = json_data["access_token"]

# Print the token (for debugging)
print("Access Token:", access_token)

# Make the curl call
url = "https://suna-backend-273014074769.us-central1.run.app/api/billing/subscription"
curl_cmd = [
    "curl",
    "-H", f"Authorization: Bearer {access_token}",
    url
]
print("\nRunning curl command:")
print(" ".join(curl_cmd))
subprocess.run(curl_cmd) 